# .github/release.yml

changelog:
  authors:
    - protorians
  categories:
    - title: Create `Attribution` support
      labels:
        - '*'
    - title: Create `AttributionSlot` support
      labels:
        - '*'
    - title: Create `resolveAttrib` function
      labels:
        - '*'
    - title: Create `resolveAttribName` function
      labels:
        - '*'
    - title: Create `resolveAttribNames` function
      labels:
        - '*'
    - title: Create `attrib` facade
      labels:
        - '*'
    - title: Create `attribSlot` facade
      labels:
        - '*'
