# .github/release.yml

changelog:
  authors:
    - protorians
  categories:
    - title: Create `Attribution`
      labels:
        - '*'
    - title: Create `AttributionSlot`
      labels:
        - '*'
    - title: Create `resolveAttrib`
      labels:
        - '*'
    - title: Create `resolveAttribName`
      labels:
        - '*'
    - title: Create `resolveAttribNames`
      labels:
        - '*'
